Appsilon/mbaza

- app/components/AnimalsPlot.tsx
- app/components/Map.css
- app/components/Map.tsx
- app/components/ObservationsTable.tsx
- app/constants/ObservationsData.ts
- app/containers/ExplorePage.tsx
- package.json
- yarn.lock
#5 solves 2/3 points in the task.
Done: 
- display on plot true loaded data with number of animals for each category per day
- fixed error when user cancel from file browser
- fixed the layout/rescaling problems
- fixed the scroll problem
> Explore page display data

- models/runner/functions.py
Apply two fixes:
* Change the way image directory structure is parsed (according to new data provided by Robbie).
* Accept uppercase image file extensions.
> Fix bugs related to image metadata loading

- app/components/Classifier.tsx
- models/.gitattributes
- models/runner/README.md
This PR should fix the broken Serengeti model and ensure it won't break again; it also cleans up some code which handles model paths.
> Cleanup model

- models/runner/functions.py
This PR fixes a tiny path parsing bug. @marekrogala, would you please repackage the models for Windows with this PR and update them on our Drive so I can finish testing #88?
> Fix Windows path parsing in the classifier script

- .editorconfig
- app/components/AnimalsPlot.tsx
- app/components/Classifier.tsx
- app/components/ObservationsTable.tsx
- app/constants/ObservationsData.ts
- models/runner/README.md
- models/runner/functions.py
- models/runner/main.py
Closes #65. To test this PR, please run the classifier script on a sample dataset and verify, that the `output.csv` file has `date` column properly inferred from `exif_datetime` and `path_date` columns.
> Extract dates from image paths in the classifier script

- .gitignore
- app/app.global.css
- app/components/Map.tsx
- app/constants/ObservationsData.ts
- package.json
- yarn.lock
Closes #59
This PR adds a display of photos on the map: one thumbnail on the map itself, thumbnails in the popup and full photos view once you click to see all.
> Display photos on map

- app/components/Classifier.tsx
- app/components/PythonLogViewer.tsx
> Add a spinner to indicate when the classifier is running

- app/components/Classifier.tsx
> Let user choose between Serengeti and Gabon model

- app/app.html
- app/assets/translations.json
- app/components/AnimalsPlot.tsx
- app/components/Classifier.tsx
- app/components/Map.tsx
- app/components/PythonLogViewer.tsx
- app/components/Sidebar.tsx
- app/components/SidebarItem.tsx
- app/components/explorerFilters.tsx
- app/components/explorerMetrics.tsx
- app/constants/Routes.ts
- app/containers/App.tsx
- app/containers/ExplorePage.tsx
- app/containers/HomePage.tsx
- app/index.tsx
With this PR, all translations are in `app/assets/translations.json` file. The translation keys have now variable-like names, so that we can use interpolation and other `i18next` features. No fallback is set, so when you set language to French all missing keys will display just the key name.
> Move translations to a JSON file

- app/menu.ts
Closes #55
Super minimal version of menu that makes sense.
Not supporting i18n here, as i18n is loaded after the menu, and it would be more complicated to use i18n here.
Goal of this PR is to make sure there are no options in the menu that don't make sense.
> Update + remove unnecessary menu items

- app/assets/translations.json
French translations added and some English text updated. I've not tested this.
> Added French text

- app/components/explorerMetrics.tsx
> Fix display of long metric description.

- app/components/Classifier.tsx
- app/components/ObservationsTable.tsx
Closes #111 
We are using the directory that is designed to contain app configuration, that will not be overwritten on update.
> Models directory

- models/runner/functions_video.py
- models/runner/main_process_videos.py
> Add scripts to extract frames from videos

- app/components/Classifier.tsx
Closes an issue which appears when biomonitoring stations file is not available
> do not pass gridfile if it doesnt exist

- app/assets/translations.json
- app/components/explorerFilters.tsx
- app/containers/ExplorePage.tsx
Please merge PR #137 first. Closes #134.
Adds a range slider to the explore page allowing user to set a certainty threshold.
> Certainty threshold

- package.json
- yarn.lock
Please check if you can still run `yarn`, `yarn dev` etc.
> Update node-sass to 6.0.1 so it works with Node v16

- models/runner/README.md
Add more specific instructions for Python installation.
> Further improve Python dev docs

- app/components/Map.tsx
- app/components/ObservationsTable.tsx
- app/components/explorerFilters.tsx
- app/constants/ObservationsData.ts
- app/containers/ExplorePage.tsx
- app/utils/readObservationsCsv.ts
Some refactoring which appeared on the way to #160.
1. The `ObservationsData` type replaced with `Observation[]`. It used to be a trivial wrapper for this single field.
2. The `chooseFile()` function (called in the "Explore results") page rewritten using `async`.
3. A new file for a simple `readObservationsCsv()` function created. This will need to be further organized / refactored, but I think it's a step in a good direction.
Please try to break the app / test functionalities. It's pure refactoring PR - there should be no changes in behavior.
> Refactor in preparation to implement event batching

- app/components/Map.tsx
> chore: remove images from inside map circles

- README.md
Fix typo and mention Node.js version in README.
> Fix typo and mention Node.js version in README

- package-lock.json
- package.json
- src/renderer/components/Map.tsx
Closes #315
* Migrated from the deprecated tooltip version to a newer version.
* Run the app.
* Click on the marker.
* Hover on the species to display tooltip.
> feat: Fixed tooltip

- assets/map-style.json
- src/main/util.ts
- src/renderer/components/Sidebar.tsx
- src/renderer/containers/App.tsx
- src/renderer/containers/HomePage.tsx
Closes #330 
* Fixed assets that failed to load on windows machine.
* Run the app and view all images, logos and map.
> bugfix: Fixed assets path errors on windows

- src/renderer/components/CertaintyFilter.tsx
> Fix certainty slider filtering

- assets/translations.json
- src/renderer/components/Map.tsx
- src/renderer/components/MaximizedObservationCard.tsx
- src/renderer/components/ObservationCard.tsx
- src/renderer/components/ObservationsInspector.tsx
- src/renderer/constants/typings.d.ts
- src/renderer/containers/ExplorePage.module.scss
- src/renderer/containers/ExplorePage.tsx
- src/renderer/styles/app.global.scss
- src/renderer/utils/exportPhotos.ts
- src/renderer/utils/readObservationsCsv.ts
> Specify csv file and database with photos locations

- src/renderer/components/ExplorerFilters.tsx
- src/renderer/constants/typings.d.ts
- src/renderer/containers/ExplorePage.tsx
- src/renderer/utils/formatLabel.ts
> Jakub filter by clicked station 301

- README.md
- assets/translations.json
- release/app/package-lock.json
- release/app/package.json
- src/renderer/containers/HomePage.tsx
1. Bump version to 2.0.0.
2. Update README with a "links" section.
3. Remove "early development version" warning and add missing translation.
> Release v2.0.0

- README.md
- src/common/models.ts
- src/renderer/components/Classifier.tsx
Use consistent naming for our models:
I'll rename the models on Drive accordingly once this PR is merged.
> Consistently name models
